apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kiuvwp4h4-nodejs-gitops
  description: This is GitOps manifest for kiuvwp4h4-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: kiuvwp4h4-nodejs
    janus-idp.io/tekton: kiuvwp4h4-nodejs 
    backstage.io/kubernetes-id: kiuvwp4h4-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kiuvwp4h4-nodejs
